name: test

on:
  workflow_run:
    workflows: ['check trigger']
    types: [completed]
  workflow_dispatch:

jobs:
  image_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Bulid and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/caddy-cloudflare:latest
        labels: |
          org.opencontainers.image.source = "https://github.com/honnip/caddy-cloudflare"

  no-update:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo There\'s no new commit.
        exit 0;
