name: check trigger

# run everyday
on:
  schedule:
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Check whether there's new commit
        run: exit $(curl -s https://api.github.com/repos/caddyserver/caddy-docker/commits/master | jq -r "((now - (.commit.author.date | fromdateiso8601) )  / (60*60*24)  | trunc)")

