name: main
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs: 
      status: ${{ steps.check.conclusion }}
    steps:
      - name: check
        run: exit $(curl -s https://api.github.com/repos/caddyserver/caddy-docker/commits/master | jq -r "((now - (.commit.author.date | fromdateiso8601) )  / (60*60*24)  | trunc)")

  bulid:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 'success'
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Bulid and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/caddy-cloudflare:latest
      
  make-action-success:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 'failure'
    steps:
      - name: say
        run: echo "There's no new commit"
    
