name: main
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps: 
    - id: status
      name: check if there's new commit
      run: exit $(curl -s https://api.github.com/repos/caddyserver/caddy-docker/commits/master | jq -r "((now - (.commit.author.date | fromdateiso8601) )  / (60*60*24)  | trunc)")
    - name: Checkout
      if: steps.status.conclusion == 'success'
      uses: actions/checkout@v2
    - name: Set up QEMU
      if: steps.status.conclusion == 'success'
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      if: steps.status.conclusion == 'success'
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      if: steps.status.conclusion == 'success'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Bulid and Push
      if: steps.status.conclusion == 'success'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/caddy-cloudflare:latest
    
